### ISSUE TITLE
Error while using it.

### ISSUE THREAD

**Issue by fusionstrings** [conventional-changelog/conventional-recommended-bump#1]
I am getting following error while running `conventional-recommended-bump` as suggested in docs.

``` javascript
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Readable.emit (events.js:74:15)
    at DestroyableTransform._transform (C:\Users\dshuk4\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\git-raw-commits\index.js:48:16)
    at DestroyableTransform.Transform._read (C:\Users\dshuk4\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\git-raw-commits\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (C:\Users\dshuk4\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\git-raw-commits\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (C:\Users\dshuk4\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\git-raw-commits\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:323:12)
    at writeOrBuffer (C:\Users\dshuk4\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\git-raw-commits\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:309:5)
    at DestroyableTransform.Writable.write (C:\Users\dshuk4\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\git-raw-commits\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:236:11)
    at Socket.ondata (stream.js:51:26)
    at Socket.emit (events.js:117:20)
```

**Comment by stevemao** [comment]
What does it say if you catch the error event? What does it say if you `git log` and your settings?

**Comment by fusionstrings** [comment]
Following are details. BTW I am getting same error while "conventional-recommended-bump" is installed globally and running command `conventional-recommended-bump` from CLI.

**caught error**

```
fatal: unrecognized argument: ------------------------'

[TypeError: Uncaught, unspecified "error" event.]
```

**setting in gulpfile**

``` javascript
import conventionalRecommendedBump from 'conventional-recommended-bump';

gulp.task('cbump', () => {
    conventionalRecommendedBump({
      preset: 'angular'
    }, function(err, releaseAs) {
      console.log('releaseAs', releaseAs);
    });
});
```

**GIT log**

```
commit c1e1534350b87c11bbcad399bc523b35055dcb7a
Author: Dilip Kr. Shukla <contact@fusionstrings.com>
Date:   Thu Jul 2 16:58:42 2015 +0530

    feat(changelog): add gulp task for automatic changelog

    Added gulp task for automatic changelog

    Closes #2

commit 8b6d22ed2f6eebf6f489cf3260bc3c72bc474099
Author: Dilip Kr. Shukla <contact@fusionstrings.com>
Date:   Thu Jul 2 15:03:22 2015 +0530

    feat(changelog): auto changelog

    Added auto changelog

    Closes #1

commit 4951c43b680d26a52ef74f0a8c0c2072cffb1665
Author: Dilip Kr. Shukla <contact@fusionstrings.com>
Date:   Wed Jul 1 23:15:36 2015 +0530

    Added readme

commit 9db7f51b5ae16765d22a8c5f96528365753ce066
Author: Dilip Kr. Shukla <contact@fusionstrings.com>
Date:   Wed Jul 1 23:07:26 2015 +0530

    2nd commit

commit 66a2ca432a109edd09a8e1c979238a0993d2624e
Author: Dilip Kr. Shukla <contact@fusionstrings.com>
Date:   Thu Jun 25 13:21:23 2015 +0530

    initial commit
```

**Comment by stevemao** [comment]
Are you on windows? Can you try swapping `git-raw-commits` with the latest?

**Comment by fusionstrings** [comment]
Yes, I am using windows 7 Pro.
I updated `git-raw-commits` from 0.0.7 to 0.0.8 but still same error.

**Comment by stevemao** [comment]
I don't have a windows machine. can you see what's wrong with the shell script on windows?
The template is
https://github.com/stevemao/git-raw-commits/blob/master/index.js#L22-L25
I thought it was fixed by https://github.com/stevemao/git-raw-commits/pull/4
PR welcome. Thanks.

**Comment by fusionstrings** [comment]
Sorry my bad, Indeed latest version of **git-raw-commits** fixes issue. Somehow it was still referring to old version.

A look at PR helped me to catch it.

**Comment by stevemao** [comment]
I'll bump the version soon. Thanks.

**Comment by fusionstrings** [comment]
Thanks a lot for your quick help and apologies for treating this issue as stackoverflow thread and not coming up with more descriptive title.

**Comment by stevemao** [comment]
It's fine. This is an open source project so if you have any issue, try to solve it together with other people :D
